#!/bin/bash

ZNC='../znc/znc'
ZNC_LUA_PATH='../znc/?.lua'

export LUA_PATH=$ZNC_LUA_PATH

function test() {
  echo -ne "\033[38;5;8m"
  echo "znc $1 asm.s"
  echo -ne "\033[39m"

  eval $ZNC $1 asm.s >/dev/null 2>/dev/null
  RESULT=$?

  if [ $RESULT -ne 0 ]; then
    echo -e "$1: \tFAILED COMPILER RETURNED ERROR $RESULT"
    exit 1
  fi

  echo -ne "\033[38;5;8m"
  echo "gcc -g -m64 asm.s -o a.out"
  echo -ne "\033[39m"

  gcc -g -m64 asm.s -o a.out
  RESULT=$?

  if [ $RESULT -ne 0 ]; then
    echo -e "$1: \tFAILED ASSEMBLER RETURNED ERROR $RESULT"
    exit 1
  fi

  echo -ne "\033[38;5;8m"
  echo -e "./a.out"
  echo -ne "\033[39m"

  ./a.out
  RESULT=$?

  echo -ne "\033[39m"
  if [ $RESULT == $2 ]; then
    printf "%-30s \033[38;5;10mPASSED\033[39m\n" "$1 -> $RESULT"
  else
    printf "%-30s \033[38;5;9mFAILED\033[39m EXPECTED $2\n" "$1 -> $RESULT"
    exit 1
  fi
}

# TODO: Pick up where we left off

test 'src/basic-add.zn' 6
test 'src/cmp.zn' 49
test 'src/if.zn' 7

rm -f a.out

